### ISSUE TITLE
RMerosivity finding time_gap incorrectly

### ISSUE THREAD

**Issue by rbcarvin** [USGS-R/Rainmaker#15]
RMerosvity calculates the erosive power of rainfall. There are currently three empirical formulas in the function, and the user can choose which method to use. All three methods calculate an incremental energy for each timestep of data, then sum up energy over the whole storm to use in the erosivity formula.

The energy formulas use an incremental intensity, which is found using the difference in time from the previous row. The issue is: to find the time_gap it currently just looks back one row - it really needs to determine if that row is at the beginning of an event, and if it is then it needs to subtract the minimum time interval present in the dataset from that row's time. This is similar to how RMevents finds a start time, I tried to apply that code here, but failed. Please Help @limnoliver @ldecicco-USGS 

"rain.test.csv" is available in the r-data file on my fork.
How it worked before:
```r
#prep some data to use: 
Raw.test <- (read.csv("D:/RCode/Rainmaker/data/rain.test.csv"))
PrecipPrep <- RMprep(df = Raw.test,prep.type = 3,date.type = 1,dates.in = "date",cnames.in = "gage01")
PrecipEvents <- RMevents_sko(df = PrecipPrep,ieHr = 2,rainthresh = 0,rain = "rain",time = "pdate")
PrecipEventList <- PrecipEvents$storms2
StormSummary <- RMIntense(df = PrecipPrep,date = "pdate",rain = "rain",df.events = PrecipEventList,
                          sdate = "StartDate",edate = "EndDate",depth = "rain")

#find incremental energy
df$time_gap[-1] <- diff(df$pdate, lag = 1)
df$intensity <- 60*df[[rain]]/df$time_gap
df$energy <- df[[rain]]*(1099*(1-0.72*exp(-2.08*df$intensity)))
#sum energy for each storm
  for(i in 1:nrow(StormSummary)){
    storm_i <- filter(df, pdate >= StormSummary$StartDate[i],
                      pdate <= StormSummary$EndDate[i])
    StormSummary$energy[i] <- sum(storm_i$energy, na.rm = TRUE)
    
  }
#calculate erosivity
StormSummary$erosivity <- 0.01*StormSummary$I30*StormSummary$energy
```
How I tried to fix it
```r
ieMin <- 120
dif_time <- diff(df[[time]])
timeInterval <- min(dif_time)
df$time_gap <- NA
  
  # loop that finds the time gap between each row
  for (i in 2:nrow(df)){
    if (dif_time[[i-1]] <= ieMin) {
      df$time_gap[i] <- diff(df$pdate, lag = 1)
    } else {
      df$time_gap[i] <- df$pdate[1] - timeInterval
    }
  }
  df$intensity <- 60*df[[rain]]/df$time_gap
```

If this isn't enough info to recreate the issue at your desk, I am happy to demonstrate. Right now it gives me 50 (or more) warnings, and returns columns of zeroes for energy and erosivity

**Comment by limnoliver** [comment]
I would use the `event` output from `RMevents_sko`. And then something like this:

`if (df$events[i] != df$events[i-1]) {
    df$StartDate[i] <- df$StartDate[i]-timeInterval
}`

**Comment by rbcarvin** [comment]
I was not able to get RMerosivity to compute correctly. I pushed my attempt to my fork... 

I think the following from the RMIntense function might be useful to borrow:
```r
#   Isolate individual events and Compute max x-min intensity for each event 
    #   period: compute sum rain and divide by duration. Report x-min intensity 
    #   in units/hr
    
    for (j in 1:nrow(df.events)) {
      subdf <- df[df[,date] >= df.events[j,sdate] & df[,date] <= df.events[j,edate],]
      # Initialize intensity vector
      intensity <- numeric(length=nrow(subdf))
      
      for (k in 1:nrow(subdf)){
        enddate <- subdf[k,date]+x
        bdate <- subdf[k,date]
        
        subdf2 <- subdf[subdf[,date] >= bdate & subdf[,date] < enddate,]
        intensity[k] <- sum(subdf2[,rain])/(x/60/60)
        
        #      k;bdate;enddate;intensity[k];max(subdf2$rain)
      }
```

**Comment by limnoliver** [comment]
Okay - I don't have my head wrapped around the erosivity function completely. But, one solution is to calculate "event" again (as in `RMevents_SKO`) . Will need to at `ieHr` as a function input. But then, you can calculate time differences using this code:

`ieMin = 60*ieHr
  #find incremental energy
  df <- df[df[rain] != 0,]
  df <- df[df[rain] > 0.00001,]
  df["event"] <- NA
  df[1, "event"] <- 1
  
  dif_time <- diff(df[,'pdate'])
  timeInterval <- min(dif_time)
  
  for (i in 2:nrow(df)){
    if (dif_time[[i-1]] >= ieMin) {
      df$event[i] <- df$event[i-1] + 1
    } else {
      df$event[i] <- df$event[i-1]
    }
  }`

Then `dif_time` becomes `time_gap`. I don't have time to implement this today (leaving in 20 mins) but I think this is the solution!

**Comment by limnoliver** [comment]
This is now implemented through a `tipsbystorm` output from `RMevents`, which now is an input to RMerosivity
