### ISSUE TITLE
Hydroevents

### ISSUE THREAD

**Issue by rbcarvin** [USGS-R/Rainmaker#51]
Folks have been using RMevents to identify their event start and end times to input to HydroVol, which finds the volume of a hydrograph during an event. They're using this at sites that go to 0 between events, or that have a constant threshold below which they know it isn't a runoff event. In the past people had slightly varying methods to find event start and end times. Todd has a specific way, that doesn't exactly match how RMevents works. Instead of subtracting the minimum time step to find the event start, he's requesting a function that uses the time from the row prior to the first flow value >0, and also uses the row after the last flow value >0. (The last and first rows of the dry period). The method acknowledges that there's some flow volume in the time between the last dry time-punch and the first wet time-punch, and that flow didn't stop at the last wet time-punch but some time between then and the first dry time. 

Instead of changing RMevents, I suggested making a Hydroevents function, that essentially is RMevents, but with this nuance.

**Comment by srcorsi-USGS** [comment]
Agreed--RMevents was intended to identify rainfall events, but not flow events. Perhaps a similar function that uses streamflow input and whatever thresholds and other parameters to define hydrograph events. This could be pretty complex given the nature of hydrographs, superimposed events, snowmelt, ...  I am not sure this really belongs in Rainmaker, but sounds more like a function for hydrotools.

**Comment by limnoliver** [comment]
This got bumped up in priority and is now implemented in the function `discharge_events`. Please test and pass along any issues!
