### ISSUE TITLE
Suggested fix for hourly rainfall data

### ISSUE THREAD

**Issue by arielreed** [USGS-R/Rainmaker#66]
I am working with hourly rain accumulation data and noticed that [RMevents.R](https://github.com/USGS-R/Rainmaker/blob/eed744a6d8d04e24afd31d208ccbdf02c5809f85/R/RMevents.R) assumes that the time interval in the provided dataset is always minutes (there is a hard-coded conversion from hours to minutes [here](https://github.com/USGS-R/Rainmaker/blob/eed744a6d8d04e24afd31d208ccbdf02c5809f85/R/RMevents.R#L30)). However, the base R function `diff` will return units of hours or minutes based on the interval it detects (`diff` is used [here](https://github.com/USGS-R/Rainmaker/blob/eed744a6d8d04e24afd31d208ccbdf02c5809f85/R/RMevents.R#L46)).

Since `ieHr` is a user-provided parameter in hours, I have a solution that detects whether `ieHr` needs to be converted to minutes or remain in hours for a valid time comparison. Let me know if I should open a PR.

**Comment by ldecicco-USGS** [comment]
Hi Ariel, if you'd like to open a pull request I'd be happy to take a look. At the moment we don't have many resources to do enhancements, but I could certainly see if the PR would fit our needs. Thanks for reaching out!
